[package]
name = "xtask"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
clap.workspace = true
xshell.workspace = true
eyre.workspace = true
color-eyre.workspace = true
